POST HTTP://localhost:3001/login
Content-Type: application/json

{
  "email": "fulano@gmail.com",
  "senha": "123456"
}

###

DELETE HTTP://localhost:3001/logout
Authorization: 19e33d6b0c5855f396293903460491a6

###

GET HTTP://localhost:3001/usuarios/10
Authorization: 982a690557e51bb768e5ac3f4b878a3f

###

POST HTTP://localhost:3001/usuarios
Content-Type: application/json
Authorization: 982a690557e51bb768e5ac3f4b878a3f

{
  "nome": "Maradona Cheirador",
  "email": "maradona@gmail.com",
  "idPerfil": 2,
  "senha": "casadepraia123"
}

###

PUT HTTP://localhost:3001/usuarios/10
Content-Type: application/json
Authorization: 982a690557e51bb768e5ac3f4b878a3f

{
  "nome": "Maradona Cheirador de Pó",
  "email": "maradonacheirador@gmail.com",
  "idPerfil": "2",
  "criadoEm": "2022-04-08T21:44:09.940Z",
  "atualizadoEm": "2022-04-08T21:44:09.940Z"
}
