POST HTTP://localhost:3001/login
Content-Type: application/json

{
  "email": "fulano@gmail.com",
  "senha": "123456"
}

###

DELETE HTTP://localhost:3001/logout
Authorization: 19e33d6b0c5855f396293903460491a6

###

GET HTTP://localhost:3001/usuarios/4
Authorization: 1755666da5d5985371ec2d48c7d629aa

###

POST HTTP://localhost:3001/usuarios
Content-Type: application/json
Authorization: 5a4e1ea7fc04f2258ce3969c8a870a8a

{
  "nome": "Beto Barbosa",
  "email": "beto@gmail.com",
  "idPerfil": 1,
  "senha": "casadepraia123"
}

###

PUT HTTP://localhost:3001/usuarios/4
Content-Type: application/json
Authorization: 1755666da5d5985371ec2d48c7d629aa

{
  "nome": "Tulio Maravilha",
  "email": "pelemaradonatulio@gmail.com",
  "idPerfil": "2",
  "criadoEm": "2022-04-08T21:44:09.940Z",
  "atualizadoEm": "2022-04-08T21:44:09.940Z"
}
